### ISSUE TITLE
Textures and Flags not Working

### ISSUE THREAD

**Issue by 45Classic** [DurtyFree/altv-cloth-tool#1]
I have the problem that when I try to make altV clothes with the tool, the textures are not loaded and the "isHighHeel" flag is not adopted for shoes. So the clothes are in the game without the textures and their flags which were set in the Tool.

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
