### ISSUE TITLE
Female feet high heels

### ISSUE THREAD

**Issue by sangyoo91** [DurtyFree/altv-cloth-tool#15]
When female shoes are added as addons (_u tag models, havent tested with _r), they have a few problems. 

1. They are either lifted up from the ground or not depending on shoe previously selected shoe. (Default to one which are high heels)
2. Even when putting the on the ground by selecting a non high heel and rendering added on shoes, to people who just saw the character, the character will look afloat in mid air (has to toggle again to make ped look not afloat) This issue might be restricted to FiveM as I dont have an environment to test this on other platforms.

**Comment by Nicoo34** [comment]
feet ydd needs to be imported with _r
feet ytd needs to be imported with _uni
please use readme.

**Comment by Nicoo34** [comment]
Last versions automaticly rename the shoes to made them work too.

**Comment by DurtyFree** [comment]
Like @Nicoo34 said pls try with last version, it should also work if you name it properly.

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
