### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by justnukezz** [DurtyFree/altv-cloth-tool#17]
I have the following error:
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "D:\#010 etwas\map\1\eup\kleidung\mp_m_freemode_01_male_freemode_valentines\teef_000_u.ydd" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.File.Copy(String sourceFileName, String destFileName)
   bei altClothTool.App.Builders.AltvResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\AltvResourceBuilder.cs:Zeile 70.
   bei altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:Zeile 51.
   bei altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:Zeile 18.

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Some file seem to not be existing anymore: "D:#10 etwas\map\1\eup\kleidung\mp_m_freemode_01_male_freemode_valentines\teef_000_u.ydd"
