### ISSUE TITLE
Error when trying to build a hat for Alt:V

### ISSUE THREAD

**Issue by Phill030** [DurtyFree/altv-cloth-tool#19]
After i imported 1 ydd and 10 ytd textures, i tried to build but it returned errors
![VirtualBoxVM_ts9SBbE0tV](https://user-images.githubusercontent.com/50775241/120906125-de8f7d00-c624-11eb-9dc2-a5673c8c7fd3.png)

**Comment by DurtyFree** [comment]
@Phill030 Please try another output folder for building

**Comment by Phill030** [comment]
i already tried. I tried with admin, without admin, changed folder to D: / C:. I've tried everything

**Comment by DurtyFree** [comment]
@Phill030 try renaming the files & folders different, there seems to be something illegal in the file path

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
