### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by zxs25310250** [DurtyFree/altv-cloth-tool#23]
I have the following error:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) 位置 H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:行号 315
   在 altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) 位置 H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:行号 23

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Place input files in different folder or select different output folders. 
Path seems to contain illegal characters.

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
