### ISSUE TITLE
Pants not loading in on alt:V

### ISSUE THREAD

**Issue by lsvMoretti** [DurtyFree/altv-cloth-tool#6]
When importing pants (lower_000_r) for example, they're not showing up in the game.

https://i.imgur.com/xYGLKP0.png

When browsing through the pants (My command is /c 4 133 0) and above, nothing is showing from here on.

**Comment by DurtyFree** [comment]
Hi @lsvMoretti please provide example altv-cloth tool project file, including some ydd / ytd to test with.

**Comment by lsvMoretti** [comment]
Before Import:

https://i.imgur.com/Vhrfdfg.png

Inside the Program:
https://i.imgur.com/T9ybfSc.png

After Build:
https://i.imgur.com/1F45qwB.png

**Comment by R3D44** [comment]
Did anyone fix that issue with the Pants on Alt:V?

**Comment by xxlio109** [comment]
I tested
altv-cloth-tool v1.2   no show
altv-cloth-tool v1.1   no show 
altv-cloth-tool v1.0   no show

altv-cloth-tool 0.0.4  is good

**Comment by DurtyFree** [comment]
Pls try with latest version: https://github.com/DurtyFree/altv-cloth-tool/releases/tag/1.3

**Comment by DurtyFree** [comment]
Closing this as there is no reply, latest version might fix this.
